// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4_Y87npQ6P_SSIPKNO1kTpI80nAf-PI',
    appId: '1:703878788378:web:41a6200e050f7f48e428a3',
    messagingSenderId: '703878788378',
    projectId: 'good-movies-53cc5',
    authDomain: 'good-movies-53cc5.firebaseapp.com',
    storageBucket: 'good-movies-53cc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDswZe4QxEvbEPeTezEvd-AqqPHAQaEw',
    appId: '1:703878788378:android:32f6b0bcef7431b1e428a3',
    messagingSenderId: '703878788378',
    projectId: 'good-movies-53cc5',
    storageBucket: 'good-movies-53cc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lYaLqvo-L9_u4N6QOch_KQsQmdkc_Js',
    appId: '1:703878788378:ios:2d455f37924e3d60e428a3',
    messagingSenderId: '703878788378',
    projectId: 'good-movies-53cc5',
    storageBucket: 'good-movies-53cc5.firebasestorage.app',
    iosBundleId: 'com.example.goodMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8lYaLqvo-L9_u4N6QOch_KQsQmdkc_Js',
    appId: '1:703878788378:ios:2d455f37924e3d60e428a3',
    messagingSenderId: '703878788378',
    projectId: 'good-movies-53cc5',
    storageBucket: 'good-movies-53cc5.firebasestorage.app',
    iosBundleId: 'com.example.goodMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4_Y87npQ6P_SSIPKNO1kTpI80nAf-PI',
    appId: '1:703878788378:web:3cc0d9f8f65f787ee428a3',
    messagingSenderId: '703878788378',
    projectId: 'good-movies-53cc5',
    authDomain: 'good-movies-53cc5.firebaseapp.com',
    storageBucket: 'good-movies-53cc5.firebasestorage.app',
  );
}
